# Generated by Django 3.0.9 on 2020-10-27 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pic', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=255)),
                ('last', models.CharField(max_length=255)),
                ('pict', models.CharField(max_length=1000, null=True)),
                ('appearances', models.PositiveIntegerField(null=True)),
                ('status', models.CharField(choices=[('Dead', 'Dead'), ('Alive', 'Alive')], max_length=5)),
                ('age', models.PositiveIntegerField(null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('weapon', models.CharField(blank=True, max_length=255, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='got.House')),
            ],
        ),
    ]
