# Generated by Django 3.0.9 on 2020-11-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='title',
        ),
        migrations.AddField(
            model_name='character',
            name='titles',
            field=models.ManyToManyField(blank=True, related_name='characters', to='got.Title'),
        ),
    ]
